namespace SurfTicket.Application.Exceptions
{
    public enum SurfErrorCode
    {
        GENERIC_ERROR = 1000,
        USER_NOT_FOUND = 2000,
        USER_WRONG_PASSWORD = 2001,
        USER_EMAIL_ALREADY_USED = 2002,
        USER_NOT_CONFIRMED = 2003,
        USER_ALREADY_CONFIRMED = 2004,
        USER_INVALID_VERIFICATION_TOKEN = 2005,
        UNAUTHORIZED = 2006,
        MERCHANT_EXCEED_LIMIT = 3000,
        MERCHANT_VIOLATE_PERMISSION = 3001,
        MERCHANT_USER_NOT_FOUND = 3002,
        MERCHANT_NOT_FOUND = 3003,
        MERCHANT_CREATE_FAILED = 3004,
        VENUE_NOT_FOUND = 3100,
        VENUE_CREATE_FAILED = 3101,
        SUBSCRIPTION_NOT_FOUND = 4000,
        SUBSCRIPTION_CREATE_FAILED = 4001,
        PLAN_NOT_FOUND = 4002,
    }
}
